<?xml version="1.0" encoding="utf-8"?>
<definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.mining.echallan.ifms.cmcltd.com/" name="MiningVerificationService" targetNamespace="http://service.mining.echallan.ifms.cmcltd.com/" xmlns="http://schemas.xmlsoap.org/wsdl/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="https://www.odishatreasury.gov.in:443/echallanservices/MiningVerificationService?xsd=1" namespace="http://service.mining.echallan.ifms.cmcltd.com/" />
    </xsd:schema>
  </types>
  <message name="getStatus">
    <part name="parameters" element="tns:getStatus" />
  </message>
  <message name="getStatusResponse">
    <part name="parameters" element="tns:getStatusResponse" />
  </message>
  <portType name="MiningVerificationService">
    <operation name="getStatus">
      <input message="tns:getStatus" />
      <output message="tns:getStatusResponse" />
    </operation>
  </portType>
  <binding name="MiningVerificationServicePortBinding" type="tns:MiningVerificationService">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <operation name="getStatus">
      <soap:operation soapAction="" />
      <input>
        <soap:body use="literal" />
      </input>
      <output>
        <soap:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="MiningVerificationService">
    <port name="MiningVerificationServicePort" binding="tns:MiningVerificationServicePortBinding">
      <soap:address location="https://www.odishatreasury.gov.in:443/echallanservices/MiningVerificationService" />
    </port>
  </service>
</definitions>